[package]
name = "guess_game"
version = "0.1.0"
edition = "2021"
authors = ["Superman"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfonts = "1.1.4"
rand = "0.8.5"

